---
title: "Ciceron Group, Barcelona October 24th 2019"
output: 
  flexdashboard::flex_dashboard:
    theme: sandstone
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
```

```{r load libraries}

library(flexdashboard)
library(dplyr)
library(knitr)
library(kableExtra)
library(plotly)
library(formattable)
library(readxl)
library(DT)
library(lubridate)
library(chron)
library(ggplot2)
library(vistime)
library(scales)
library(tidyverse)

```


Budget {data-navmenu="financials"}
===================================== 


```{r table}
tables <- function(x){

x %>% select(1:5) %>% mutate(total = paste("EUR", format(round(total, 2L),nsmall = 2,big.mark = ","))) %>% 
  kable(
   format = "html", escape = F) %>% kable_styling(fixed_thead =   T,bootstrap_options = c("striped","condensed","hover","responsive")) %>%
row_spec(0, bold = T, color = "white", background = "black")  %>% 
  column_spec(1, width = "8em") %>% 
  column_spec(5,bold = TRUE, width = "8em")}
```


_**Ciceron Group**_ {data-width=850}
-------------------------------------------

### Budget as of July 8, 2019

<br><br>

```{r budget_table}

budget <- read_excel("rooming.xlsx", sheet = "bud", range = "B13:G27") 
budget <- sapply(budget, as.character)
budget[is.na(budget)] <- ""
budget <- data.frame(budget, stringsAsFactors = FALSE)
class(budget$bud_units) <- "numeric"
class(budget$bud_cost) <- "numeric"
class(budget$bud_total) <- "numeric"

names(budget) <- c("date","description","units","unit cost","total","category")


budget[nrow(budget),] <- c("","","<strong>Total</strong>","",sum(budget$total),"")

class(budget$total) <- "numeric"

tables(budget)

```

_**Ciceron group**_{data-width=150}
-------------------------------------------

```{r budget_sorting}


budget <- budget[-nrow(budget),]

bud_transfers <- budget %>% filter(category == "transfer") %>% summarise(total= sum(total)) %>% prettyNum(big.mark = ",")

bud_activity <- budget %>% filter(category == "activity") %>% summarise(total= sum(total))%>% prettyNum(big.mark = ",")

bud_hotel <- budget %>% filter(category == "hotel") %>% summarise(total = sum(total))%>% prettyNum(big.mark = ",")

bud_restaurant <- budget %>% filter(category == "restaurant") %>%  summarise(total = sum(total)) %>% prettyNum(big.mark = ",")

bud_audiovisuals <- budget %>% filter(category == "audiovisuals") %>%  summarise(total = sum(total)) %>% prettyNum(big.mark = ",")

```

<br>

### hotel

```{r hotel_box}

valueBox(bud_hotel, 
         icon = "fa-h-square", 
         caption = "Euros in Hotel",
         color = "#fcffc2")
```


### transfers

```{r transfer_box}

valueBox(bud_transfers, icon = "fa-shuttle-van",
         caption = "Euros in transfers",
         color = "#c6e2ff")

```

### restaurants

```{r restaurant_box}

valueBox(bud_restaurant, 
         icon = "fa-utensils", 
         caption = "Euros in offsite restaurants",
         color = "#fdc9d9")
```



